Repository opendatahub-io/ai-edge, pull requests merged in 2023-11, with the labels that each got.

#144 Add support for git credentials for ACM Subscriptions.
  acm/registration/near-edge/base/kustomization.yaml
  acm/registration/near-edge/base/nameReference.yaml
  acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml
  acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
Labels: kind/enhancement, priority/normal

#112 [RHOAIEDGE-15] Adding option to fetch from git
  pipelines/README.md
  pipelines/tekton/build-container-image-pipeline/build-container-image-pipeline.yaml
  pipelines/tekton/build-container-image-pipeline/build-container-image-pipelinerun-bike-rentals.yaml
  pipelines/tekton/build-container-image-pipeline/build-container-image-pipelinerun-tensorflow-housing.yaml
  pipelines/tekton/build-container-image-pipeline/check-model-and-containerfile-exists.yaml
  pipelines/tekton/build-container-image-pipeline/kserve-download-model.yaml
Labels: kind/enhancement, priority/blocker, lgtm, approved

#173 Create Metrics CM in correct place on core cluster
  README.md
  acm/odh-core/acm-observability/files/metrics_list.yaml
  acm/odh-core/acm-observability/kustomization.yaml
Labels: lgtm, approved
