Repository opendatahub-io/ai-edge, pull requests merged in 2023-10, with the labels that each got.

#113 Use official Tekton `github-open-pr` task
  pipelines/tekton/gitops-update-pipeline/kustomization.yaml
Labels: kind/enhancement, priority/low

#128 The metrics service is not used in the test-mlflow-image-pipeline in any way.
  pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml
Labels: priority/low, king/bugfix

#76 Add Make recipe to allow for easier testing of changes
  DEVELOPMENT.md
  Makefile
  README.md
  test/acm/bike-rental-app/kustomization.yaml
  test/acm/tensorflow-housing-app/kustomization.yaml
  test/gitops/bike-rental-app/kustomization.yaml
  test/gitops/tensorflow-housing-app/kustomization.yaml
Labels: kind/documentation, kind/enhancement, priority/normal

#127 Delete the deployment at the end of test, allow using upon-end parameter to "stop" or "keep".
  pipelines/README.md
  pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml
Labels: kind/enhancement, priority/low

#124 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: kind/documentation, kind/enhancement, priority/normal

#123 Expand description of the GitOps pipeline, update defaults to GitHub.
  pipelines/README.md
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/example-git-credentials-secret.yaml
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-bike-rentals.yaml
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-tensorflow-housing.yaml
  pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml
Labels: kind/documentation, kind/enhancement, priority/low

#139 Order components based on their usage, losen version requirements.
  README.md
Labels: kind/documentation, kind/enhancement, priority/low

#142 The gitea-ai-edge-rhoai-edge-acm repo has image digests that do not exist on quay.
  acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml
  acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
Labels: priority/high, king/bugfix

#145 Clarify that Gitea is optional.
  README.md
Labels: kind/documentation, kind/enhancement, priority/low

#137 File the pull request with information about the latest built and pushed image for the model
  pipelines/README.md
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-bike-rentals.yaml
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-tensorflow-housing.yaml
  pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml
  pipelines/tekton/gitops-update-pipeline/kustomization.yaml
  pipelines/tekton/gitops-update-pipeline/test-mlflow-retrieve-image-info-task.yaml
  pipelines/tekton/test-mlflow-image-pipeline/kustomization.yaml
  pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml
  pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipelinerun-bike-rental.yaml
  pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipelinerun-tensorflow-housing.yaml
  pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-record-image-task.yaml
Labels: kind/documentation, kind/enhancement, priority/high

#143 Use digests of newest images in quay.io/rhoai-edge/ repositories.
  acm/odh-edge/apps/bike-rental-app/kustomization.yaml
  acm/odh-edge/apps/tensorflow-housing-app/kustomization.yaml
Labels: kind/enhancement, priority/normal

#140 Restructure the top-level README to make the order of steps clearer.
  README.md
  acm/registration/near-edge/base/near-edge.yaml
Labels: kind/documentation, kind/enhancement, priority/high

#147 Improve issues readability
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: kind/documentation, kind/enhancement, priority/low
