Repository opendatahub-io/ai-edge, pull requests merged in 2023-09, with the labels that each got.

#65 Make skopeo push to unique tag
  pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml
Labels: kind/bug, kind/enhancement, priority/blocker

#54 Update image reference in edge Deployment
  pipelines/README.md
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/example-git-credentials-secret.yaml
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-bike-rentals.yaml
  pipelines/tekton/gitops-update-pipeline/example-pipelineruns/gitops-update-pipelinerun-tensorflow-housing.yaml
  pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml
  pipelines/tekton/gitops-update-pipeline/kustomization.yaml
Labels: kind/documentation, kind/enhancement, priority/high

#75 Clone Containerfiles from Git, Use Build Args in Containerfiles
  pipelines/containerfiles/Containerfile.openvino.mlserver.mlflow
  pipelines/containerfiles/Containerfile.seldonio.mlserver.mlflow
  pipelines/models/bike-rentals-auto-ml/Containerfile
  pipelines/models/tensorflow-housing/Containerfile
  pipelines/tekton/azureml-container-pipeline/azureml-container-pipeline.yaml
  pipelines/tekton/azureml-container-pipeline/azureml-container-pipelinerun-bike-rentals.yaml
  pipelines/tekton/azureml-container-pipeline/azureml-container-pipelinerun-tensorflow-housing.yaml
  pipelines/tekton/azureml-container-pipeline/check-model-and-containerfile-exists.yaml
  pipelines/tekton/azureml-container-pipeline/check-model-exists.yaml
  pipelines/tekton/azureml-container-pipeline/kustomization.yaml
Labels: kind/enhancement, priority/low

#79 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: kind/documentation
