Repository opendatahub-io/ai-edge, pull requests merged in 2024-03, with the labels that each got.

#216 RHOAIENG-437: Add instructions to fetch models from different s3 regions
  pipelines/tekton/aiedge-e2e/templates/credentials-s3.secret.yaml.template
Labels: lgtm, approved, jira/valid-reference

#217 RHOAIENG-1119: Don't rely on imagestream in image info task
  pipelines/tekton/aiedge-e2e/tasks/retrieve-build-image-info.task.yaml
Labels: lgtm, approved, jira/valid-reference

#218 RHOAIENG-1119: Add new candidate-image-tag-reference parameter
  pipelines/tekton/aiedge-e2e/aiedge-e2e.bike-rentals.pipelinerun.yaml
  pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml
  pipelines/tekton/aiedge-e2e/aiedge-e2e.tensorflow-housing.pipelinerun.yaml
  pipelines/tekton/aiedge-e2e/tasks/retrieve-build-image-info.task.yaml
Labels: lgtm, approved, jira/valid-reference

#219 RHOAIENG-1119: Update result names that assume "internal" image
  pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml
  pipelines/tekton/aiedge-e2e/tasks/retrieve-build-image-info.task.yaml
Labels: lgtm, approved, jira/valid-reference

#223 The PipelineRun YAML where git fetch approach work out of box is the tensorflow housing one.
  pipelines/README.md
Labels: lgtm, approved

#224 Rework the Data for testing the model inferencing endpoint section to focus on the default example setups.
  pipelines/README.md
Labels: lgtm, approved

#225 Make the GitOps pipeline find the target registry URL again
  pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml
  pipelines/tekton/gitops-update-pipeline/test-mlflow-retrieve-image-info-task.yaml
Labels: lgtm, approved

#228 RHOAIENG-4992 - Remove useMergedBuildTestPipeline parameter from gito…
  pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml
  pipelines/tekton/gitops-update-pipeline/test-mlflow-retrieve-image-info-task.yaml
Labels: lgtm, approved

#227 RHOAIENG-3458: Add a models command to the CLI
  .gitignore
  Makefile
  cli/Makefile
  cli/cmd/main.go
  cli/cobra.yaml
  cli/go.mod
  cli/go.sum
  cli/pkg/commands/models.go
  cli/pkg/commands/root.go
  cli/pkg/commands/root_test.go
Labels: lgtm, approved, jira/valid-reference

#222 RHOAIENG-3457: Add an inital root CLI
  .gitignore
  Makefile
  cli/Makefile
  cli/cmd/main.go
  cli/cobra.yaml
  cli/go.mod
  cli/go.sum
  cli/pkg/commands/root.go
  cli/pkg/commands/root_test.go
Labels: approved, do-not-merge/hold, jira/valid-reference

#229 RHOAIENG-2787: Let ArgoCD create namespace, rather than using ACM Policy
  acm/odh-edge/base/namespace.yaml
  acm/registration/near-edge/base/near-edge.yaml
  acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml
  acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#233 Remove orphaned Policy and PlacementBinding references
  acm/registration/near-edge/overlays/bike-rental-app/kustomization.yaml
  acm/registration/near-edge/overlays/tensorflow-housing-app/kustomization.yaml
  acm/registration/near-edge/test/bike-rental-app/kustomization.yaml
  acm/registration/near-edge/test/tensorflow-housing-app/kustomization.yaml
Labels: lgtm, approved

#239 Fix link to the metrics_list.yaml.
  docs/byo-mgmt-gitops.md
Labels: lgtm, approved

#237 The PipelineRuns are in separate files.
  pipelines/README.md
Labels: lgtm, approved

#238 What the Task builds is actually an image, not a container.
  pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml
Labels: lgtm, approved
